services:
  chromium:
    container_name: chromium
    image: selenium/standalone-chromium:latest
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: webapp
    ports:
      - "8080:8080"
